// goto https://www.fluentu.com/blog/english/useful-english-proverbs/
// open dev console and paste:
// JSON.stringify(Array.prototype.slice.call(document.querySelectorAll("h3")).map(o=>o.innerText.split(".").slice(1,2).join("").trim()).filter(s=>s!=""))
var a_s_saying = [
    "The grass is always greener on the other side of the fence",
    "Don’t judge a book by its cover",
    "Strike while the iron is hot",
    "Too many cooks spoil the broth",
    "You can’t have your cake and eat it too",
    "Many hands make light work",
    "When in Rome, do as the Romans do",
    "Don’t cross the bridge until you come to it",
    "Honesty is the best policy",
    "Practice makes perfect",
    "Where there’s a will, there’s a way",
    "Look before you leap",
    "Beggars can’t be choosers",
    "Don’t make a mountain out of an anthill",
    "An apple a day keeps the doctor away",
    "The early bird catches the worm",
    "Better late than never",
    "The cat is out of the bag",
    "Two wrongs don’t make a right",
    "Always put your best foot forward",
    "Rome wasn’t built in a day",
    "It’s better to be safe than sorry",
    "Don’t bite the hand that feeds you",
    "The squeaky wheel gets the grease",
    "Don’t bite off more than you can chew",
    "You made your bed, now you have to lie in it",
    "Actions speak louder than words",
    "It takes two to tango",
    "Don’t count your chickens before they hatch",
    "It’s no use crying over spilled milk",
    "Don’t put all your eggs in one basket",
    "People in glass houses shouldn’t throw stones",
    "A rolling stone gathers no moss",
    "First things first",
    "Still waters run deep",
    "If it ain’t* broke, don’t fix it",
    "Curiosity killed the cat",
    "Learn to walk before you run",
    "Money doesn’t grow on trees",
    "My hands are tied",
    "It’s the tip of the iceberg",
    "No news is good news",
    "Out of sight, out of mind",
    "If you scratch my back, I’ll scratch yours",
    "Ignorance is bliss",
    "Easy come, easy go",
    "The forbidden fruit is always the sweetest",
    "Every cloud has a silver lining",
    "You can’t make an omelet without breaking a few eggs",
    "Close but no cigar"
];

export {
    a_s_saying
}